### ISSUE TITLE
Don't escape special characters

### ISSUE THREAD

**Issue by gavr123456789** [treeform/print#18]
I mean its harder to read strings with \n:  
![image](https://user-images.githubusercontent.com/30507409/134997011-fb5ecd1a-856d-45c5-afab-82fc7a086440.png)  
vs  
![image](https://user-images.githubusercontent.com/30507409/134997221-c14fddf8-6189-40e4-ae61-f7c4fd0cc6ad.png)

**Comment by treeform** [comment]
Sorry I don't think I will be fixing this error. If you want to print string to the output use echo. If you want to print the string so that you can see the special formatting characters use print. Thats the point of print is to see what is in your strings. Hopefully anything print outputs you can take back int put it into nim source code.
